@extends('layouts.app')

@section('content')
<div class="min-h-screen bg-gray-50">
    <div class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between">
                <div>
                    <h1 class="text-3xl font-bold text-gray-900">Transcript</h1>
                    <p class="mt-2 text-gray-600">{{ $transcript->student->user->name ?? 'Student' }} — Academic Year {{ $transcript->academic_year }}</p>
                </div>
                <div class="flex space-x-3">
                    <a href="{{ route('admin.transcripts.index') }}" class="inline-flex items-center px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white font-medium rounded-md">Back to Transcripts</a>
                    <a href="{{ route('admin.transcripts.pdf', $transcript) }}" class="inline-flex items-center px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-medium rounded-md">Download PDF</a>
                </div>
            </div>
        </div>
    </div>

    @if(session('success'))
        <div class="max-w-7xl mx-auto px-4 py-2"><div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">{{ session('success') }}</div></div>
    @endif
    @if(session('info'))
        <div class="max-w-7xl mx-auto px-4 py-2"><div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded">{{ session('info') }}</div></div>
    @endif

    <div class="max-w-5xl mx-auto py-6 sm:px-6 lg:px-8">
        <div class="bg-white shadow rounded-lg overflow-hidden">
            <div class="p-6">
                <div class="grid grid-cols-2 gap-6 mb-8">
                    <div>
                        <p class="text-sm text-gray-500">Student</p>
                        <p class="font-medium text-gray-900">{{ $transcript->student->user->name ?? '—' }}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-500">Class</p>
                        <p class="font-medium text-gray-900">{{ $transcript->student->classRoom->name ?? '—' }}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-500">Academic Year</p>
                        <p class="font-medium text-gray-900">{{ $transcript->academic_year }}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-500">CGPA</p>
                        <p class="font-medium text-gray-900">{{ number_format($transcript->cgpa ?? 0, 2) }}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-500">Generated</p>
                        <p class="font-medium text-gray-900">{{ $transcript->generated_at?->format('M d, Y H:i') ?? '—' }}</p>
                    </div>
                    <div>
                        <p class="text-sm text-gray-500">Generated by</p>
                        <p class="font-medium text-gray-900">{{ $transcript->generatedBy->name ?? '—' }}</p>
                    </div>
                </div>

                @if(!empty($transcript->terms_data) && is_array($transcript->terms_data))
                    <h2 class="text-lg font-semibold text-gray-900 mb-4">Terms</h2>
                    @foreach($transcript->terms_data as $termBlock)
                        <div class="mb-8">
                            <h3 class="text-md font-medium text-gray-800 mb-2">{{ $termBlock['term'] ?? 'Term' }} — GPA: {{ number_format($termBlock['gpa'] ?? 0, 2) }}</h3>
                            <div class="border border-gray-200 rounded-lg overflow-hidden">
                                <table class="min-w-full divide-y divide-gray-200">
                                    <thead class="bg-gray-50">
                                        <tr>
                                            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Subject</th>
                                            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Mid-term</th>
                                            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Final</th>
                                            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Total</th>
                                            <th class="px-4 py-2 text-left text-xs font-medium text-gray-500 uppercase">Grade</th>
                                        </tr>
                                    </thead>
                                    <tbody class="bg-white divide-y divide-gray-200">
                                        @foreach($termBlock['subjects'] ?? [] as $row)
                                            <tr>
                                                <td class="px-4 py-2 text-sm text-gray-900">{{ $row['subject'] ?? '—' }}</td>
                                                <td class="px-4 py-2 text-sm text-gray-600">{{ $row['mid_term'] ?? '—' }}</td>
                                                <td class="px-4 py-2 text-sm text-gray-600">{{ $row['final'] ?? '—' }}</td>
                                                <td class="px-4 py-2 text-sm text-gray-600">{{ $row['total'] ?? '—' }}</td>
                                                <td class="px-4 py-2 text-sm font-medium text-gray-900">{{ $row['grade'] ?? '—' }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    @endforeach
                @else
                    <p class="text-gray-500">No term data available for this transcript.</p>
                @endif

                @if($transcript->remarks)
                    <div class="mt-6 pt-6 border-t border-gray-200">
                        <p class="text-sm text-gray-500">Remarks</p>
                        <p class="text-gray-900">{{ $transcript->remarks }}</p>
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
